name = "The Lost Age"
author = "kubino12_"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "721e58a33efc4522ea12a73f341c70c16a5a158ae08b9872b2320f8256ccb0fe"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
