name = "The Lost Age"
author = "kubino12_"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4b7ef2c951f0d18cda0e6787b06feb317072f1376943393468c96e630c56abaf"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
